In [ ]:
# Import required libraries
import pandas as pd
import numpy as np

In [ ]:
# Load the credit card fraud dataset
df = pd.read_csv('/content/creditcard.csv')
# Display the first five rows
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# Check the size of the dataset
print(df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

(284807, 31)
Number of rows: 284807
Number of columns: 31

In [ ]:
# Check column data types and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [ ]:
# Check for duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())
# Remove duplicate rows
df.drop_duplicates(inplace=True)
df.duplicated().sum()

Number of duplicate rows: 1081

np.int64(0)

In [ ]:
# Check missing values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# Fill missing numerical values with their column mean
df['V26']= df['V26'].fillna(df['V26'].mean())
df['V27']= df['V27'].fillna(df['V27'].mean())
df['V28']= df['V28'].fillna(df['V28'].mean())
df['Amount']= df['Amount'].fillna(df['Amount'].mean())
# Remove rows where the target variable is missing
df = df.dropna(subset=['Class'])
# Convert the target variable to integer
df['Class'] = df['Class'].astype(int)
print(df.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# Check the distribution of normal and fraudulent transactions
print(df['Class'].value_counts())

Class
0    283253
1       473
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
train, test = train_test_split(df, test_size=0.2, random_state=42,stratify=df['Class'])

print("Training data:", train.shape)
print("Testing data:",test.shape)

Training data: (226980, 31)
Testing data: (56746, 31)

In [ ]:
# Separate features and target variable
X_train = train.drop('Class', axis=1)
y_train = train['Class']
X_test = test.drop('Class', axis=1)
y_test = test['Class']

In [ ]:
# Check the dimensions of training and testing data
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (226980, 30)
y_train: (226980,)
X_test: (56746, 30)
y_test: (56746,)

In [ ]:
# Check class distribution before applying SMOTE
print("Training classes:")
print(y_train.value_counts())

print("\nTesting classes:")
print(y_test.value_counts())

Training classes:
Class
0    226602
1       378
Name: count, dtype: int64

Testing classes:
Class
0    56651
1       95
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE only to the training data
smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train,
    y_train
)

In [ ]:
# Compare class distribution before and after SMOTE
print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(y_train_resampled.value_counts())

Before SMOTE:
Class
0    226602
1       378
Name: count, dtype: int64

After SMOTE:
Class
0    226602
1    226602
Name: count, dtype: int64

In [ ]:
!pip install -q xgboost

In [ ]:
from xgboost import XGBClassifier

In [2]:
# Create the XGBoost classification model
from xgboost import XGBClassifier
model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

In [ ]:
# Train XGBoost on the SMOTE-balanced training data
model.fit(X_train_resampled, y_train_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
# Predict normal/fraud classes for unseen test data
y_pred = model.predict(X_test)
print(y_pred[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [ ]:
# Get the predicted probability of fraud (Class 1)
y_prob = model.predict_proba(X_test)[:, 1]
print(y_prob[:20])

[1.8194320e-05 1.3332377e-05 6.6518893e-05 4.2915097e-05 4.8498355e-04
 6.6593399e-05 1.4831803e-05 1.0251669e-06 1.2912649e-04 4.6567711e-06
 4.5791567e-06 2.2802351e-04 9.3879402e-07 7.3017298e-05 2.4159428e-05
 2.7069638e-05 1.6160181e-03 1.7942286e-05 9.7426364e-06 1.0574747e-05]

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [ ]:
# Evaluate the model using different classification metrics
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9993479716632009
Precision: 0.8085106382978723
Recall   : 0.8
F1 Score : 0.8042328042328042
ROC-AUC  : 0.9683800815519584

In [ ]:
# Test different probability thresholds
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

for threshold in thresholds:

    y_threshold = (y_prob >= threshold).astype(int)

    precision = precision_score(y_test, y_threshold)
    recall = recall_score(y_test, y_threshold)
    f1 = f1_score(y_test, y_threshold)

    print(
        f"Threshold: {threshold:.1f} | "
        f"Precision: {precision:.4f} | "
        f"Recall: {recall:.4f} | "
        f"F1: {f1:.4f}"
    )

Threshold: 0.1 | Precision: 0.4815 | Recall: 0.8211 | F1: 0.6070
Threshold: 0.2 | Precision: 0.6179 | Recall: 0.8000 | F1: 0.6972
Threshold: 0.3 | Precision: 0.6786 | Recall: 0.8000 | F1: 0.7343
Threshold: 0.4 | Precision: 0.7451 | Recall: 0.8000 | F1: 0.7716
Threshold: 0.5 | Precision: 0.8085 | Recall: 0.8000 | F1: 0.8042
Threshold: 0.6 | Precision: 0.8444 | Recall: 0.8000 | F1: 0.8216
Threshold: 0.7 | Precision: 0.8941 | Recall: 0.8000 | F1: 0.8444
Threshold: 0.8 | Precision: 0.9048 | Recall: 0.8000 | F1: 0.8492
Threshold: 0.9 | Precision: 0.9157 | Recall: 0.8000 | F1: 0.8539

In [ ]:
# Select the threshold with the highest F1 score
best_threshold = 0.9

y_final = (y_prob >= best_threshold).astype(int)

print("Final threshold:", best_threshold)
print("Final predictions:")
print(y_final[:20])

Final threshold: 0.9
Final predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [ ]:
print("Final prediction distribution:")
print(pd.Series(y_final).value_counts())

Final prediction distribution:
0    56663
1       83
Name: count, dtype: int64

In [ ]:
# Create a table of feature importance scores
feature_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

   Feature  Importance
14     V14    0.664284
10     V10    0.061762
12     V12    0.040782
4       V4    0.040450
17     V17    0.024945
8       V8    0.013687
3       V3    0.012683
11     V11    0.012487
1       V1    0.012470
9       V9    0.008904
13     V13    0.008249
19     V19    0.007687
22     V22    0.006480
7       V7    0.006329
29  Amount    0.006245
18     V18    0.006113
0     Time    0.006047
2       V2    0.006030
25     V25    0.005932
21     V21    0.005514
26     V26    0.005159
23     V23    0.005109
5       V5    0.004975
16     V16    0.004849
20     V20    0.004816
6       V6    0.004673
15     V15    0.004337
28     V28    0.003467
24     V24    0.003295
27     V27    0.002240